<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_header item</name>
   <tag></tag>
   <elementGuidId>81057cbe-1df8-4bd8-893c-fbd6e1d6ac41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.header.item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-header-menu']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f1933da8-6755-45e6-acfb-77c8e2acfd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header item</value>
      <webElementGuid>bcb35570-8626-4235-a396-02b48e904118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-header-menu&quot;)/div[@class=&quot;header item&quot;]</value>
      <webElementGuid>ec130903-4b51-41b4-95b9-1efd5eb8937e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-header-menu']/div</value>
      <webElementGuid>f4cbac57-49c9-4e2a-b860-fce164af81b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>00bf701f-79ae-4475-9ca9-a19b07f28a87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
